# Generated by Django 4.1.5 on 2023-01-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 1, 20, 19, 50, 56, 907176, tzinfo=datetime.timezone.utc
                ),
                upload_to="images/",
            ),
            preserve_default=False,
        ),
    ]
