# Generated by Django 4.1.5 on 2023-01-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
